blueprint:
  name: Philips Hue Smart Dimmer Switch V2 (RWL022)
  description: ''
  source_url: https://github.com/timkeane5/ha-automations/blob/develop/PhilipsRWL022.yaml
  domain: automation
  input:
    dimmer_switch:
      name: Dimmer Switch
      description: The controller device to use for the automation.
      default: ''
      selector:
        device:
          filter:
          - model: RWL022
          multiple: false
    helper_last_event:
      name: Helper - Last Event (Required)
      description: Input Text used to store the last event sent from the controller.
        This is required as the Hue Dimmer Switch sends out multiple events for each
        button press and the meaning of an event can change depending on what the
        previous event was. You will need to create this manually.
      default: ''
      selector:
        entity:
          domain:
          - input_text
          multiple: false
    on_press_action:
      name: Power Short Press (Optional)
      description: Action to perform on short press of power button
      default: []
      selector:
        action: {}
    on_hold_action:
      name: Power Long Press/Hold (Optional)
      description: Action to perform on long press/hold of Power button. If Power Long Press Type is set to Long Press this action will occur once, if it is set to Hold this action will repeat until the button is released.
      default: []
      selector:
        action: {}
    on_long_press_type:
      name: Power Long Press Type
      description: Choose whether a long press of the power button should be considered a Long Press (fires once the button is released), or a Hold (fires continuously until the button is released)
      default: 'long'
      selector:
        select:
          options:
            - label: Long Press
              value: 'long'
            - label: Hold
              value: 'hold'
    on_double_press_action:
      name: Power Double Press (Optional)
      description: Action to perform on double press of Power button
      default: []
      selector:
        action: {}
    on_press_all_single:
      name: Treat All Presses as Single Presses (Power Button)
      description: If if this is set, the automation will respond to every press of the power button ignoring the double press and any of the other multi-press events the controller sends.
      default: false
      selector:
        boolean:
    off_short_press_action:
      name: Hue Short Press (Optional)
      description: Action to perform on short press of Hue button
      default: []
      selector:
        action: {}
    off_hold_action:
      name: Hue Long Press/Hold (Optional)
      description: Action to perform on long press/hold of Hue button. If Hue Long Press Type is set to Long Press this action will occur once, if it is set to Hold this action will repeat until the button is released.
      default: []
      selector:
        action: {}
    off_long_press_type:
      name: Hue Long Press Type
      description: Choose whether a long press of the Hue button should be considered a Long Press (fires once the button is released), or a Hold (fires continuously until the button is released)
      default: 'long'
      selector:
        select:
          options:
            - label: Long Press
              value: 'long'
            - label: Hold
              value: 'hold'
    off_double_press_action:
      name: Hue Double Press (Optional)
      description: Action to perform on double press of Hue button
      default: []
      selector:
        action: {}
    off_press_all_single:
      name: Treat All Presses as Single Presses (Hue Button)
      description: If if this is set, the automation will respond to every press of the hue button ignoring the double press and any of the other multi-press events the controller sends.
      default: false
      selector:
        boolean:
    up_short_press_action:
      name: Up Short Press (Optional)
      description: Action to perform on short press of Hue button
      default: []
      selector:
        action: {}
    up_hold_action:
      name: Up Long Press/Hold (Optional)
      description: Action to perform on long press/hold of Up button. If Up Long Press Type is set to Long Press this action will occur once, if it is set to Hold this action will repeat until the button is released.
      default: []
      selector:
        action: {}
    up_long_press_type:
      name: Up Long Press Type
      description: Choose whether a long press of the Up button should be considered a Long Press action (fires once the button is released), or a Hold action (fires continuously until the button is released)
      default: 'hold'
      selector:
        select:
          options:
            - label: Long Press
              value: 'long'
            - label: Hold
              value: 'hold'
    up_double_press_action:
      name: Up Double Press (Optional)
      description: Action to perform on double press of Up button
      default: []
      selector:
        action: {}
    up_press_all_single:
      name: Treat All Presses as Single Presses (Up Button)
      description: If if this is set, the automation will respond to every press of the up button ignoring the double press and any of the other multi-press events the controller sends.
      default: false
      selector:
        boolean:
    down_short_press_action:
      name: Down Short Press (Optional)
      description: Action to perform on short press of Down button
      default: []
      selector:
        action: {}
    down_hold_action:
      name: Down Long Press/Hold (Optional)
      description: Action to perform on long press/hold of Down button. If Down Long Press Type is set to Long Press this action will occur once, if it is set to Hold this action will repeat until the button is released.
      default: []
      selector:
        action: {}
    down_long_press_type:
      name: Down Long Press Type
      description: Choose whether a long press of the down button should be considered a Long Press (fires once the button is released), or a Hold action (fires continuously until the button is released)
      default: 'hold'
      selector:
        select:
          options:
            - label: Long Press
              value: 'long'
            - label: Hold
              value: 'hold'
    down_double_press_action:
      name: Down Double Press (Optional)
      description: Action to perform on double press of Down button
      default: []
      selector:
        action: {}
    down_press_all_single:
      name: Treat All Presses as Single Presses (Down Button)
      description: If if this is set, the automation will respond to every press of the down button ignoring the double press and any of the other multi-press events the controller sends.
      default: false
      selector:
        boolean:
variables:
  helper_last_event_var: !input helper_last_event
  on_long_press_type: !input on_long_press_type
  off_long_press_type: !input off_long_press_type
  up_long_press_type: !input up_long_press_type
  down_long_press_type: !input down_long_press_type
  on_press_all_single : !input on_press_all_single
  off_press_all_single : !input off_press_all_single
  up_press_all_single : !input up_press_all_single
  down_press_all_single : !input down_press_all_single
  events_to_use: ['on_press', 'on_short_release', 'on_double_press', 'on_hold', 'on_long_release', 'off_press', 'off_short_release', 'off_double_press', 'off_hold', 'off_long_release', 'up_press', 'up_short_release', 'up_double_press', 'up_hold', 'up_long_release', 'down_press', 'down_short_release', 'down_double_press', 'down_hold', 'down_long_release', 'stop' ]

trigger:
- platform: event
  event_type:
  - zha_event
  event_data:
    device_id: !input dimmer_switch

condition:
  - condition: template
    value_template: '{{ trigger.event.data.command | string in events_to_use }}'
action:

- variables:
    last_action: "{{ (states(helper_last_event_var) | from_json).a }}"
    trigger_command: "{{ trigger.event.data.command }}"

- service: input_text.set_value
  data:
    entity_id: !input helper_last_event
    value: '{{ {"a": trigger.event.data.command ,"t":as_timestamp(now())} | to_json }}'
- choose:
# BEGIN POWER BUTTON
# Short Press
  - conditions:
    - condition: template
      value_template: '{{ (on_press_all_single and trigger_command == ''on_short_release'') or (not on_press_all_single and trigger_command == ''on_press'' and last_action == ''on_short_release'') }}'
    sequence: !input on_press_action
# Double Press
  - conditions:
    - condition: template
      value_template: '{{ trigger_command == ''on_double_press'' and not on_press_all_single }}'
    sequence: !input on_double_press_action
# Long Press
  - conditions:
    - condition: template
      value_template: '{{ trigger_command == ''on_hold'' and last_action != ''on_hold'' and on_long_press_type == ''long'' }}'
    sequence: !input on_hold_action
# Hold
  - conditions:
    - condition: template
      value_template: '{{trigger_command == ''on_hold'' and last_action != ''on_hold'' and on_long_press_type == ''hold'' }}'
    sequence:
      - repeat:
          while: '{{ (((states(helper_last_event_var) | from_json).a) != ''stop'') and (((states(helper_last_event_var) | from_json).a) != ''on_long_release'') }}'
          sequence: 
          - alias: on hold action
            if: '{{ true }}'
            then: !input on_hold_action
          - alias: loop delay
            if: '{{ true }}'
            then:
            - delay: '00:00:00.250'
# END POWER BUTTON

# BEGIN HUE/OFF BUTTON
  # Short Press
  - conditions:
    - condition: template
      value_template: '{{ (off_press_all_single and trigger_command == ''off_short_release'') or (not off_press_all_single and trigger_command == ''off_press'' and last_action == ''off_short_release'') }}'
    sequence: !input off_short_press_action
  # Double Press
  - conditions:
    - condition: template
      value_template: '{{ trigger_command == ''off_double_press'' and not off_press_all_single }}'
    sequence: !input off_double_press_action
  # Hue Long Press
  - conditions:
    - condition: template
      value_template: '{{ trigger_command == ''off_hold'' and last_action != ''off_hold'' and off_long_press_type == ''long'' }}' # only get first hold event
    sequence: !input off_hold_action
  # Hue Hold
  - conditions:
    - condition: template
      value_template: '{{trigger_command == ''off_hold'' and last_action != ''off_hold'' and off_long_press_type == ''hold'' }}' # only get first hold event
    sequence:
      - repeat:
          while: '{{ (((states(helper_last_event_var) | from_json).a) != ''stop'') and (((states(helper_last_event_var) | from_json).a) != ''off_long_release'') }}'
          sequence: 
          - alias: off hold action
            if: '{{ true }}'
            then: !input off_hold_action
          - alias: loop delay
            if: '{{ true }}'
            then:
            - delay: '00:00:00.250'
# END HUE/OFF BUTTON

# BEGIN UP BUTTON
  # Short Press
  - conditions:
    - condition: template
      value_template: '{{ (up_press_all_single and trigger_command == ''up_short_release'') or (not up_press_all_single and trigger_command == ''up_press'' and last_action == ''up_short_release'') }}'
    sequence: !input up_short_press_action
  # Double Press
  - conditions:
    - condition: template
      value_template: '{{ trigger_command == ''up_double_press'' and not up_press_all_single }}'
    sequence: !input up_double_press_action
  # Long Press
  - conditions:
    - condition: template
      value_template: '{{ trigger_command == ''up_hold'' and last_action != ''up_hold'' and up_long_press_type == ''long'' }}' # only get first hold event
    sequence: !input up_hold_action
  # Hold
  - conditions:
    - condition: template
      value_template: '{{trigger_command == ''up_hold'' and last_action != ''up_hold'' and up_long_press_type == ''hold'' }}' # only get first hold event
    sequence:
      - repeat:
          while: '{{ ((states(helper_last_event_var) | from_json).a) != ''stop'' }}'
          sequence: 
          - alias: up hold action
            if: '{{ true }}'
            then: !input up_hold_action
          - alias: loop delay
            if: '{{ true }}'
            then:
            - delay: '00:00:00.100'
# END UP BUTTON

# BEGIN DOWN BUTTON
  # Short Press
  - conditions:
    - condition: template
      value_template: '{{ (down_press_all_single and trigger_command == ''down_short_release'') or (not down_press_all_single and trigger_command == ''down_press'' and last_action == ''down_short_release'') }}'
    sequence: !input down_short_press_action
  # Double Press
  - conditions:
    - condition: template
      value_template: '{{ trigger_command == ''down_double_press'' and not down_press_all_single }}'
    sequence: !input down_double_press_action
  # Long Press
  - conditions:
    - condition: template
      value_template: '{{ trigger_command == ''down_hold'' and last_action != ''down_hold'' and down_long_press_type == ''long'' }}' # only get first hold event
    sequence: !input down_hold_action
  # Hold
  - conditions:
    - condition: template
      value_template: '{{trigger_command == ''down_hold'' and last_action != ''down_hold'' and down_long_press_type == ''hold'' }}' # only get first hold event
    sequence:
      - repeat:
          while: '{{ ((states(helper_last_event_var) | from_json).a) != ''stop'' }}'
          sequence: 
          - alias: down hold action
            if: '{{ true }}'
            then: !input down_hold_action
          - alias: loop delay
            if: '{{ true }}'
            then:
            - delay: '00:00:0.250'
# END DOWN BUTTON

mode: parallel # Use parallel to allow stop command to break hold loop
